### ISSUE TITLE
[Schedule.Web & Schedule.API] Menu Inicio

### ISSUE THREAD

**Issue by Wolfteam** [Wolfteam/Schedule#2]
# TODO:

- [x] Crear la logica necesaria para generar los horarios y guardarlos en la db.

- [x] Generar los 3 tipos de formatos requeridos. Pueden ser visualizados/descargados por cualquier persona.

- [x] ~~Agregar una opcion que permita crear un nuevo semestre. La cual resetee las secciones creadas hasta los momentos, entre otros. Quizas crear una tabla con los semestres y agregar un campo semestre a las secciones para que solo me traiga la secciones acordes al semestre en el que me encuentro~~ 
Sera tratado mas a fondo en #5 

# A tener en cuenta:

- Cada semestre cambian las secciones, por lo que los periodos son importantes, una opcion que permita crear un nuevo semestre seria ideal

- Al generar los formatos debes tener en cuenta que siempre se empieza por el profesor con mayor prioridad hasta que llegas al de menor.
