### ISSUE TITLE
[Schedule.API] Permitir logearse solo si el sistema esta activo y crear tabla periodo_academico 

### ISSUE THREAD

**Issue by Wolfteam** [Wolfteam/Schedule#20]
Estas son algunas preparaciones para #2 

# TODO
- [x] Crear una tabla periodo_academico que contenga los datos básicos del mismo (id, nombre, status (unique para que solo 1 semestre pueda estar activo a la vez))

- [x] El login va a leer si hay un semestre activo, de no existir no debe dar acceso al sistema en caso de ser un usuario común. (Esto con la idea de que una vez hayan cargado los profesores sus disponibilidades, el sistema se "tumbe" para que solo el admin pueda entrar y los prof. no puedan modificar sus disponibilidades)

- [x] Agregar una relacion entre disponibilidad y semestre, lo cual permita traer las disponibilidades acordes al semestre activo.

- [x] Realizar los cambios pertinentes en los metodos de disponibilidad.

- [x] Agregar una relacion entre secciones y semestre, lo cual permita traer las secciones acordes al semestre activo.

- [x] Realizar los cambios pertinentes en los metodos de secciones.
