### ISSUE TITLE
[Schedule.Web] Menu Cargar Disponibilidad

### ISSUE THREAD

**Issue by Wolfteam** [Wolfteam/Schedule#4]
# TODO:

- [x] Debe permitir cargar la disponibilidad de un profesor haciendo click sobre los días de la semana.

- [x] ~~Los dias habilitados son de lunes a sabado, pero debe ser posible quitar o modificar dias.~~ (Algo complejo y fastidioso de hacer)

- [x] ~~Agregar algo como turnos de acuerdo a la prioridad del profesor, como el sistema de inscripciones de la universidad, de que a cierta hora te puedes logear.~~ (No tiene sentido, puesto que tu puedes guardar la disponibilidad en el orden que quieras, al final quien genera los horarios se basa en su prioridad (C-MT, DE, etc) siempre empezando por el que tenga la mayor y siempre y cuando pueda colocarlo en la disponibilidad que el profesor escogió. 

- [x]  Visualizar las horas que debe asignar acorde a su prioridad, al igual que las mismas deben ir disminuyendo a medida que vaya marcando las horas

# A tener en cuenta:

- Un administrador puede cargar la disponibilidad al profesor que quiera, mientras que un profesor solo puede cargar su propia disponibilidad.

- Solo se admiten de lunes a sabado. No se permiten seleccionar horas que se encuentren entre las 12-1pm.

- El profesor debe seleccionar siempre al menos 2 horas de clase, no puede seleccionar menos en un día.
